// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGame = `-- name: CreateGame :one
INSERT INTO games (id, red_user_id, yellow_user_id, winner_id, time_control_ms, started_at, ended_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, red_user_id, yellow_user_id, winner_id, time_control_ms, started_at, ended_at
`

type CreateGameParams struct {
	ID            uuid.UUID          `json:"id"`
	RedUserID     pgtype.UUID        `json:"red_user_id"`
	YellowUserID  pgtype.UUID        `json:"yellow_user_id"`
	WinnerID      pgtype.UUID        `json:"winner_id"`
	TimeControlMs *int32             `json:"time_control_ms"`
	StartedAt     time.Time          `json:"started_at"`
	EndedAt       pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) CreateGame(ctx context.Context, arg CreateGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, createGame,
		arg.ID,
		arg.RedUserID,
		arg.YellowUserID,
		arg.WinnerID,
		arg.TimeControlMs,
		arg.StartedAt,
		arg.EndedAt,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.RedUserID,
		&i.YellowUserID,
		&i.WinnerID,
		&i.TimeControlMs,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const createGameMove = `-- name: CreateGameMove :exec
INSERT INTO game_moves (game_id, move_number, col, played_at)
VALUES ($1, $2, $3, $4)
`

type CreateGameMoveParams struct {
	GameID     uuid.UUID `json:"game_id"`
	MoveNumber int32     `json:"move_number"`
	Col        int16     `json:"col"`
	PlayedAt   time.Time `json:"played_at"`
}

func (q *Queries) CreateGameMove(ctx context.Context, arg CreateGameMoveParams) error {
	_, err := q.db.Exec(ctx, createGameMove,
		arg.GameID,
		arg.MoveNumber,
		arg.Col,
		arg.PlayedAt,
	)
	return err
}

const listGamesForUser = `-- name: ListGamesForUser :many
SELECT id, red_user_id, yellow_user_id, winner_id, time_control_ms, started_at, ended_at FROM games
where red_user_id = $1 OR yellow_user_id = $1
ORDER BY ended_at DESC NULLS LAST
LIMIT $2
`

type ListGamesForUserParams struct {
	RedUserID pgtype.UUID `json:"red_user_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListGamesForUser(ctx context.Context, arg ListGamesForUserParams) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGamesForUser, arg.RedUserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.RedUserID,
			&i.YellowUserID,
			&i.WinnerID,
			&i.TimeControlMs,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
