// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID            uuid.UUID          `json:"id"`
	RedUserID     *uuid.UUID         `json:"red_user_id"`
	YellowUserID  *uuid.UUID         `json:"yellow_user_id"`
	WinnerID      *uuid.UUID         `json:"winner_id"`
	TimeControlMs *int32             `json:"time_control_ms"`
	StartedAt     time.Time          `json:"started_at"`
	EndedAt       pgtype.Timestamptz `json:"ended_at"`
}

type GameMove struct {
	GameID     uuid.UUID `json:"game_id"`
	MoveNumber int32     `json:"move_number"`
	Col        int16     `json:"col"`
	PlayedAt   time.Time `json:"played_at"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID               uuid.UUID          `json:"id"`
	GoogleSub        string             `json:"google_sub"`
	Email            string             `json:"email"`
	Name             string             `json:"name"`
	AvatarUrl        *string            `json:"avatar_url"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DisplayName      *string            `json:"display_name"`
	DisplayNameSetAt pgtype.Timestamptz `json:"display_name_set_at"`
}
