// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getUserByGoogleSub = `-- name: GetUserByGoogleSub :one
SELECT id, google_sub, email, name, avatar_url, created_at, updated_at, display_name, display_name_set_at FROM users
WHERE google_sub = $1
`

func (q *Queries) GetUserByGoogleSub(ctx context.Context, googleSub string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGoogleSub, googleSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.DisplayNameSetAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, google_sub, email, name, avatar_url, created_at, updated_at, display_name, display_name_set_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.DisplayNameSetAt,
	)
	return i, err
}

const updateDisplayName = `-- name: UpdateDisplayName :one
UPDATE users
SET display_name = $2,
    display_name_set_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, google_sub, email, name, avatar_url, created_at, updated_at, display_name, display_name_set_at
`

type UpdateDisplayNameParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName *string   `json:"display_name"`
}

func (q *Queries) UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateDisplayName, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.DisplayNameSetAt,
	)
	return i, err
}

const upsertUserFromGoogle = `-- name: UpsertUserFromGoogle :one
INSERT INTO users (google_sub, email, name, avatar_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (google_sub) DO UPDATE SET
    email = EXCLUDED.email,
    name = EXCLUDED.name,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = now()
RETURNING id, google_sub, email, name, avatar_url, created_at, updated_at, display_name, display_name_set_at
`

type UpsertUserFromGoogleParams struct {
	GoogleSub string  `json:"google_sub"`
	Email     string  `json:"email"`
	Name      string  `json:"name"`
	AvatarUrl *string `json:"avatar_url"`
}

func (q *Queries) UpsertUserFromGoogle(ctx context.Context, arg UpsertUserFromGoogleParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserFromGoogle,
		arg.GoogleSub,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisplayName,
		&i.DisplayNameSetAt,
	)
	return i, err
}
